# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='nully', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date_time', models.DateField(blank=True, null=True)),
                ('class_roster', models.CharField(default='nully', max_length=200)),
                ('class_query_type', models.CharField(default='nully', max_length=200)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Class_type')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(default='last_name', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_first_name', models.CharField(default='nully', max_length=100)),
                ('instructor_last_name', models.CharField(default='nully', max_length=100)),
                ('instructor_id', models.CharField(default='nully', max_length=100)),
                ('instructor_email', models.EmailField(max_length=254)),
                ('instructor_phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='nully', max_length=75)),
                ('last_name', models.CharField(default='nully', max_length=150)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('class_type', models.TextField(default='nully', max_length=200)),
                ('order_id', models.CharField(default='nully', max_length=200)),
                ('order_date', models.CharField(default='nully', max_length=200)),
                ('order_discount_code', models.CharField(default='nully', max_length=200)),
                ('class_registered', models.CharField(max_length=200)),
                ('classes_completed', models.CharField(max_length=200)),
                ('classes_incomplete', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Course')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Training_site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_site_name', models.CharField(default='nully', max_length=100)),
                ('class_street_address', models.CharField(default='nully', max_length=200)),
                ('class_street_apt_suite', models.CharField(default='nully', max_length=200)),
                ('class_city', models.CharField(default='nully', max_length=200)),
                ('training_site_state', models.CharField(default='nully', max_length=2)),
                ('training_site_country', models.CharField(default='nully', max_length=100)),
                ('training_site_zip_code', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='coursex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='classes.Student'),
        ),
        migrations.AddField(
            model_name='class_type',
            name='training_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Training_site'),
        ),
    ]
